### ISSUE TITLE
Large amounts of "whitespace" around lowercase glyphs

### ISSUE THREAD

**Issue by mattparks** [exezin/msdf-c#2]
I've noticed that msdf-c generates some glyphs, mostly lower-case glyphs, with more space around the main character data than msdfgen provides. 

Here are some examples. Glyphs generated from Roboto Regular at 32x32, a range of 1, and with autoframe.

Chars: a, @, h, c, -

Chlumsky/msdfgen:
![image](https://user-images.githubusercontent.com/4019937/73779848-0631b500-4753-11ea-85f8-a3bea0a1469a.png)
![image](https://user-images.githubusercontent.com/4019937/73781168-6b86a580-4755-11ea-8c82-55df785082cb.png)
![image](https://user-images.githubusercontent.com/4019937/73781295-9a048080-4755-11ea-8c59-d26bc52065f5.png)
![image](https://user-images.githubusercontent.com/4019937/73782311-83f7bf80-4757-11ea-83ee-41ee77ff8060.png)
![image](https://user-images.githubusercontent.com/4019937/73780481-2ca42000-4754-11ea-9cd6-25b0a5d7ca93.png)

exezin/msdf-c:
![image](https://user-images.githubusercontent.com/4019937/73779855-07fb7880-4753-11ea-912f-9a239ec6b5c5.png)
![image](https://user-images.githubusercontent.com/4019937/73781124-5ad62f80-4755-11ea-8425-5242a96ec5d6.png)
![image](https://user-images.githubusercontent.com/4019937/73781303-9d980780-4755-11ea-9f51-b410c7bd819c.png)
![image](https://user-images.githubusercontent.com/4019937/73782329-89eda080-4757-11ea-9e58-0a50991da179.png)
![image](https://user-images.githubusercontent.com/4019937/73780493-3037a700-4754-11ea-8b6f-a807c8f0d24a.png)

256x256 Example:
![image](https://user-images.githubusercontent.com/4019937/73782851-5a8b6380-4758-11ea-8438-10fe7748fba5.png)
![image](https://user-images.githubusercontent.com/4019937/73782858-5d865400-4758-11ea-81f1-3b4dc8717a97.png)

**Comment by solenum** [comment]
Interesting, I'm currently using this in my other project (https://github.com/exezin/exengine) and the final rendering results seem correct.

It's been a while since I have touched this project but I suspect I could be pre-scaling things to be the appropriate scale for what it is, so you don't have to store meta-data and scale anything when rendering them out at the end.

I'll take a look at this :+1: 

Edit;  

Could this also be the result of using the 'autoframe' option? Could you also confirm that this actually presents issues when attempting to use the generated MSDF to render a line of text?

[Here](https://github.com/exezin/exengine/blob/master/src/exengine/render/text.c) is my implementation.

**Comment by mattparks** [comment]
The rendering results are mostly correct, but with some glyphs a lot of texture space is underutilized; in comparison, msdfgen fits the glyph mutch closer to the edge of the bitmap. 

Another variable that can effect quality is `RANGE`, your constant for range does not appear to produce the same results as pxrange in msdfgen:
![msdfgen](https://user-images.githubusercontent.com/4019937/73791197-79452680-4767-11ea-8275-dab31eb5de05.png)
![msdf-c](https://user-images.githubusercontent.com/4019937/73791209-7ea27100-4767-11ea-9aab-d5ab02eb48d4.png)


msdfgen creates this glyph without autoframe (256x256):
![msdfgen](https://user-images.githubusercontent.com/4019937/73789317-2c138580-4764-11ea-94dd-22e7b47c6709.png)

**Comment by solenum** [comment]
I'm actually struggling to find the right metrics for the scale (line 975 msdf.c) using stb_truetype.h, as far as I can tell stb_truetype only supplies two functions to get this metric and the current one used produces the a larger glyph than the other function.

As for the px_range value, does changing the iteration count here produce results that look closer to that of msdfgen?
~~~~
~ main.c:121 ~
  for(int i=0; i<4; ++i)
    p += ((PX_RANGE*otf)/size)*size;
~~~~

**Comment by mattparks** [comment]
The output only looks right when both `RANGE` from msdf.c and `PX_RANGE` in main.cpp match, otherwise the shape has little antialiasing. 

Right now in main `bitmap_sdf` represents the actaual MSDF image, and `bitmap` represents the example rendered image using that sdf.  I would suggest having these two images use a seperate size value (one for thge MSDF, one for the test render).

**Comment by solenum** [comment]
That's a valid point, I'll work on that soon and also have a look into the `RANGE` and `PX_RANGE` thing, though I'm really not sure what the issue is there.

**Comment by solenum** [comment]
Hi, as of commit https://github.com/exezin/msdf-c/commit/a2b0008c70e7e4093b170082f8d4a599832bc5e0 I have implemented auto-fit, this needs some testing though.

There's no way to enable it via the command-line yet, I hadn't really planned for this to become a tool, just code one could use in their own projects but perhaps that will change soon.

Anyway, change this line in main.c as shown here (last argument enables auto-fit) and give it a test, see how it works for you.

~~~~
~ main.c:109 ~
   float *msdf = ex_msdf_glyph(&font, ex_utf8(c), size, size, &metrics, 1);
~~~~

No auto-fit:
![msdf_out](https://user-images.githubusercontent.com/5076722/73992274-83714b80-4946-11ea-9da0-2d3c30f1dee0.png)

With auto-fit:
![msdf_out](https://user-images.githubusercontent.com/5076722/73992280-89ffc300-4946-11ea-8d3b-6c4b740c887d.png)

**Comment by mattparks** [comment]
Your auto-fit is working well for me, this is what my 256x256 example looks like with auto-fit=1.
![26](https://user-images.githubusercontent.com/4019937/74045009-ab39d100-4991-11ea-9166-7410b40eda61.png)

I'm still not 100% sure how I will use `RANGE` and `PX_RANGE` in my font shader, but this is my shader:
```glsl
uniform sampler2DArray msdf;

in vec3 vTexCoords;

layout(location = 0) out vec4 outColor;

float median(float r, float g, float b) {
	return max(min(r, g), min(max(r, g), b));
}

void main() {
	vec3 msdfSample = texture(msdf, vTexCoords).rgb;
	float sigDist = median(msdfSample.r, msdfSample.g, msdfSample.b);
	float w = fwidth(sigDist);
	float opacity = smoothstep(0.5 - w, 0.5 + w, sigDist);
	outColor = vec4(1.0, 1.0, 1.0, opacity);
}
```

**Comment by solenum** [comment]
Here's my text shader,  I have to dynamically calculate the scale factor `u_scale` based on some values to keep the antialiasing consistent regardless of render size, its a bit strange but it works.  I think the reason I need to do this is as you said before, there's something wrong with the `RANGE` and `PX_RANGE` aspects of the generator.

See [here](https://github.com/exezin/exengine/blob/master/src/exengine/render/text.c#L145) for how I calculate `u_scale`, it should also be noted that `RANGE` never actually touches my shader, those values are only used for generating.

~~~~glsl
#version 330 core

in vec2 uv;

out vec4 color;

uniform sampler2D u_texture;
uniform float     u_scale;

float median(float r, float g, float b) {
    return max(min(r, g), min(max(r, g), b));
}

void main()
{
  vec3 sample = texture(u_texture, uv).rgb;
  float dist = u_scale * (median(sample.r, sample.g, sample.b) - 0.5);
  float o = clamp(dist + 0.5, 0.0, 1.0);
  color = vec4(vec3(1.0), o);
}
~~~~
